# Generated by Django 4.0.4 on 2022-05-10 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarmodel',
            name='self_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
